### PR TITLE
Frontend Information set up and connection

### PR DESCRIPTION
**Pull request by Evan-Leon**
Apologies, this is way too large of a PR, things kept leading to one another, so I will be sure to make it better in the future.
Features:
- New Navigation
  - Added, source and collection home, source and collection show and source and collection modify
- Full Crud for associations with re-renders (can test in a collection or source modify component) 
Notes:
- Still needs some styling tlc
- some suboptimal state and render behavior I am fixing
- wanted to get this up before I kept going further
  - will be cleaning up and tweaking for next pr

### CODE REVIEW

**Comment by Evan-Leon** [comment]
Additional python note:
- for some reason in mcweb/frontend/views.py i could not import VERSION from mcweb.settings, i got error 'module mcweb not found', changing the import to only settings fixed it (but I do not think this is correct) @rahulbot

**Comment by evansuslovich** [comment]
- Change variables for collectionsSlice --> setCollections and setCollection

**Comment by evansuslovich** [comment]
Change variable names for sourceSlice as well

**Comment by evansuslovich** [comment]
^^ as well as for variables in sourcesCollectionsSlice

**Comment by evansuslovich** [comment]
Great work! Fantastic!!!!!!

**Pull request merged**
